version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development

  frontend:
    build: ./my-app
    ports:
      - "3000:3000"
    volumes:
      - ./my-app:/app-fe
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
